"use client";
import React from 'react';
import { Sparkles, TrendingUp, AlertCircle, ArrowRight } from 'lucide-react';

export default function AiInsightNotificationPage() {
    return (
        <div className="min-h-screen p-6 max-w-4xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-white flex items-center gap-2">
                        <Sparkles className="text-indigo-400" />
                        Kaarya AI Insights
                    </h1>
                    <p className="text-sm text-[#8899AA] mt-1">Smart, proactive alerts generated by machine learning models analyzing your org data.</p>
                </div>
            </div>

            <div className="grid gap-6">
                {/* Attrition Risk Insight */}
                <div className="bg-gradient-to-br from-[#0A1420] to-rose-900/10 border border-rose-500/20 rounded-2xl p-6 relative overflow-hidden group">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-rose-500/10 blur-3xl rounded-full" />

                    <div className="flex items-start gap-4 relative z-10">
                        <div className="w-12 h-12 rounded-full bg-rose-500/20 flex flex-shrink-0 items-center justify-center text-rose-500">
                            <AlertCircle size={24} />
                        </div>
                        <div className="flex-1">
                            <div className="flex justify-between items-start mb-1">
                                <h3 className="text-lg font-bold text-white">High Attrition Risk Detected</h3>
                                <span className="text-xs font-bold bg-rose-500/20 text-rose-400 px-2 py-1 rounded">Urgent Insight</span>
                            </div>
                            <p className="text-sm text-[#8899AA] mb-4">Engineering department (Frontend Pod) shows early indicators of flight risk. Average tenure is at 2.1 years, with a 40% drop in pulse survey engagement.</p>

                            <div className="bg-[#060D1A] border border-[#1A2A3A] p-4 rounded-xl mb-4">
                                <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2">AI Recommended Action Line</h4>
                                <ul className="text-sm text-[#CCDDEE] space-y-2">
                                    <li className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-indigo-500" /> Schedule skip-level 1:1s with senior engineers.</li>
                                    <li className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-indigo-500" /> Review recent promotion cycles for compression.</li>
                                </ul>
                            </div>

                            <button className="text-rose-400 hover:text-rose-300 text-sm font-bold flex items-center gap-1">
                                View Full Analysis <ArrowRight size={14} />
                            </button>
                        </div>
                    </div>
                </div>

                {/* Positive Insight */}
                <div className="bg-gradient-to-br from-[#0A1420] to-emerald-900/10 border border-emerald-500/20 rounded-2xl p-6 relative overflow-hidden group">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/10 blur-3xl rounded-full" />

                    <div className="flex items-start gap-4 relative z-10">
                        <div className="w-12 h-12 rounded-full bg-emerald-500/20 flex flex-shrink-0 items-center justify-center text-emerald-400">
                            <TrendingUp size={24} />
                        </div>
                        <div className="flex-1">
                            <div className="flex justify-between items-start mb-1">
                                <h3 className="text-lg font-bold text-white">Offer Acceptance Rate Trending Up</h3>
                                <span className="text-xs font-bold bg-emerald-500/20 text-emerald-400 px-2 py-1 rounded">Positive Trend</span>
                            </div>
                            <p className="text-sm text-[#8899AA]">Your new customized offer letter workflow has increased Q3 acceptance rates by 18% compared to industry baseline.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
