"use client";

import { Sparkles, TrendingUp, AlertCircle, ArrowRight } from "lucide-react";
import Page from "@/components/ui/Page";
import Card from "@/components/ui/Card";
import Button from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";

export default function AiInsightNotificationPage() {
    return (
        <Page
            title="Kaarya AI Insights"
            subtitle="Smart, proactive alerts generated by machine learning models analyzing your org data"
            breadcrumbs={[
                { label: "Notifications", href: "/notifications" },
                { label: "AI Insights" },
            ]}
            maxWidth="900px"
        >
            <div className="space-y-6">
                {/* Attrition Risk */}
                <Card
                    padding="lg"
                    className="border-rose-500/20 bg-gradient-to-br from-[#0A1420] to-rose-900/10"
                >
                    <div className="flex items-start gap-4">
                        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-rose-500/20 text-rose-500">
                            <AlertCircle size={24} aria-hidden="true" />
                        </div>
                        <div className="flex-1">
                            <div className="mb-1 flex flex-wrap items-start justify-between gap-2">
                                <h3 className="text-lg font-bold text-white">
                                    High Attrition Risk Detected
                                </h3>
                                <Badge variant="danger">Urgent Insight</Badge>
                            </div>
                            <p className="mb-4 text-sm text-[#8899AA]">
                                Engineering department (Frontend Pod) shows early indicators of flight
                                risk. Average tenure is at 2.1 years, with a 40% drop in pulse survey
                                engagement.
                            </p>

                            <div className="mb-4 rounded-xl border border-[#1A2A3A] bg-[#060D1A] p-4">
                                <h4 className="mb-2 text-xs font-bold uppercase tracking-wider text-white">
                                    AI Recommended Action Line
                                </h4>
                                <ul className="space-y-2 text-sm text-[#CCDDEE]">
                                    <li className="flex items-center gap-2">
                                        <span
                                            className="h-1.5 w-1.5 rounded-full bg-indigo-500"
                                            aria-hidden="true"
                                        />
                                        Schedule skip-level 1:1s with senior engineers.
                                    </li>
                                    <li className="flex items-center gap-2">
                                        <span
                                            className="h-1.5 w-1.5 rounded-full bg-indigo-500"
                                            aria-hidden="true"
                                        />
                                        Review recent promotion cycles for compression.
                                    </li>
                                </ul>
                            </div>

                            <Button
                                variant="ghost"
                                size="sm"
                                iconRight={<ArrowRight size={14} aria-hidden="true" />}
                            >
                                View Full Analysis
                            </Button>
                        </div>
                    </div>
                </Card>

                {/* Positive Insight */}
                <Card
                    padding="lg"
                    className="border-emerald-500/20 bg-gradient-to-br from-[#0A1420] to-emerald-900/10"
                >
                    <div className="flex items-start gap-4">
                        <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-emerald-500/20 text-emerald-400">
                            <TrendingUp size={24} aria-hidden="true" />
                        </div>
                        <div className="flex-1">
                            <div className="mb-1 flex flex-wrap items-start justify-between gap-2">
                                <h3 className="text-lg font-bold text-white">
                                    Offer Acceptance Rate Trending Up
                                </h3>
                                <Badge variant="success">Positive Trend</Badge>
                            </div>
                            <p className="text-sm text-[#8899AA]">
                                Your new customized offer letter workflow has increased Q3 acceptance
                                rates by 18% compared to industry baseline.
                            </p>
                        </div>
                    </div>
                </Card>

                {/* AI badge */}
                <div className="flex items-center gap-2 text-xs text-[#556677]">
                    <Sparkles size={14} className="text-indigo-400" aria-hidden="true" />
                    Insights are refreshed every 6 hours by the Kaarya AI engine.
                </div>
            </div>
        </Page>
    );
}
