/**
 * Axe-core accessibility spec — runs WCAG 2A/2AA checks on every route in the
 * route catalog. Each test is named `a11y — <path>` so it can be targeted via
 * `--grep "a11y —"` in CI.
 *
 * Per-route JSON reports are written to `playwright-report/axe/<slug>.json`
 * for triage of non-blocking (minor/moderate) violations.
 *
 * Only `serious` and `critical` violations fail the test. Minor/moderate
 * violations are recorded in the JSON report but do not block CI.
 *
 * Requirements: 6.5, 14.5
 */

import fs from "node:fs";
import path from "node:path";

import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

// ---------------------------------------------------------------------------
// Route catalog — generated by `scripts/generate-route-catalog.ts` at build
// time. If the file doesn't exist yet (e.g. first checkout before a build),
// we skip gracefully rather than crashing the test runner.
// ---------------------------------------------------------------------------

interface RouteEntry {
  path: string;
  group: string;
  module: string;
  isDynamic: boolean;
  sample?: string;
}

const catalogPath = path.join(__dirname, "route-catalog.json");

let routes: RouteEntry[] = [];

if (fs.existsSync(catalogPath)) {
  const raw = fs.readFileSync(catalogPath, "utf-8");
  const allRoutes = JSON.parse(raw) as RouteEntry[];
  // Deduplicate by path — keep the first occurrence (root app/page.tsx wins over group duplicates)
  const seen = new Set<string>();
  routes = allRoutes.filter((r) => {
    if (seen.has(r.path)) return false;
    seen.add(r.path);
    return true;
  });
} else {
  // Emit a single skipped test so the suite is visible in CI output.
  test("a11y — route-catalog.json not found (run build first)", () => {
    test.skip(true, "e2e/route-catalog.json does not exist — run `npm run build` to generate it");
  });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a URL path to a filesystem-safe slug for the JSON report filename. */
function pathToSlug(urlPath: string): string {
  return urlPath
    .replace(/^\//, "")
    .replace(/\//g, "__")
    .replace(/[[\]]/g, "_")
    .replace(/[^a-zA-Z0-9_-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "") || "root";
}

/** Ensure the axe report output directory exists. */
function ensureReportDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

// ---------------------------------------------------------------------------
// Per-route axe-core tests
// ---------------------------------------------------------------------------

for (const route of routes) {
  // Use `sample` (resolved URL with real params) for navigation; fall back to
  // `path` for static routes. This ensures dynamic routes like `/employees/[id]`
  // navigate to `/employees/EMP001` rather than the literal bracket path.
  const navigateTo = route.sample ?? route.path;

  test(`a11y — ${route.path}`, async ({ page }) => {
    // Navigate and wait for network to settle so dynamic content is rendered.
    await page.goto(navigateTo, { waitUntil: "domcontentloaded" });
    // Brief pause to allow client-side rendering to complete
    await page.waitForTimeout(1000);

    // Run axe with WCAG 2A and 2AA rule sets.
    const results = await new AxeBuilder({ page })
      .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"])
      .analyze();

    // Write the full report (including minor/moderate) for triage.
    const reportDir = path.join(
      __dirname,
      "..",
      "playwright-report",
      "axe",
    );
    ensureReportDir(reportDir);

    const slug = pathToSlug(route.path);
    const reportFile = path.join(reportDir, `${slug}.json`);
    fs.writeFileSync(
      reportFile,
      JSON.stringify(
        {
          route: route.path,
          sample: navigateTo,
          timestamp: new Date().toISOString(),
          violations: results.violations,
          passes: results.passes.length,
          incomplete: results.incomplete.length,
          inapplicable: results.inapplicable.length,
        },
        null,
        2,
      ),
    );

    // Only `serious` and `critical` violations are blocking (R6.5, R14.5).
    const blocking = results.violations.filter(
      (v) => v.impact === "serious" || v.impact === "critical",
    );

    expect(
      blocking,
      `Axe found ${blocking.length} serious/critical violation(s) on ${route.path}:\n` +
        JSON.stringify(blocking, null, 2),
    ).toEqual([]);
  });
}
