"use client";
import React from "react";
import { CheckCircle2, FileText, Send, Eye, Clock, Download, ChevronRight, Briefcase } from "lucide-react";

export default function OfferAcceptance() {
    return (
        <div className="p-6 md:p-8 max-w-[1000px] mx-auto text-white">
            <div className="flex items-center justify-between mb-8">
                <div>
                    <h1 className="text-3xl font-bold mb-1">Offer Status & Tracking</h1>
                    <p className="text-sm text-[#8899AA]">Monitor the final stages of the hiring process for Rahul Sharma</p>
                </div>
                <button className="h-10 px-4 bg-[#00E5A0] text-[#060B14] text-sm font-bold rounded-xl hover:bg-[#00c98d] flex items-center gap-2 transition-colors shadow-[0_0_20px_rgba(0,229,160,0.3)]">
                    Trigger Onboarding <ChevronRight size={16} />
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

                {/* Status Tracker */}
                <div className="lg:col-span-2 space-y-6">
                    <div className="bg-[#0D1928] border border-[#1A2A3A] rounded-2xl p-6 relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-32 h-32 bg-[#00E5A0] opacity-5 blur-[80px]" />

                        <div className="flex items-center gap-4 mb-8">
                            <div className="w-14 h-14 bg-gradient-to-br from-[#00E5A0] to-[#0066FF] rounded-full flex items-center justify-center shadow-lg">
                                <CheckCircle2 size={28} className="text-white" />
                            </div>
                            <div>
                                <h2 className="text-2xl font-bold text-white mb-1">Offer Accepted! 🎉</h2>
                                <p className="text-sm text-[#8899AA]">Rahul signed the offer letter digitally 2 hours ago.</p>
                            </div>
                        </div>

                        {/* Timeline */}
                        <div className="pl-6 space-y-8 relative before:absolute before:inset-y-2 before:left-[31px] before:w-0.5 before:bg-[#1A2A3A]">

                            <div className="relative flex gap-4">
                                <div className="absolute -left-[14px] w-8 h-8 rounded-full bg-[#00E5A0] flex items-center justify-center border-4 border-[#0D1928] z-10">
                                    <CheckCircle2 size={14} className="text-[#060B14]" />
                                </div>
                                <div>
                                    <h4 className="font-bold text-white text-sm">Offer Accepted</h4>
                                    <p className="text-[11px] text-[#445566] mb-2">15 Mar 2025, 11:45 AM · IP: 192.168.1.1</p>
                                    <button className="h-8 px-3 bg-[#1A2A3A] border border-[#2A3A4A] text-xs font-semibold rounded-lg flex items-center gap-1.5 hover:text-white transition-colors">
                                        <Download size={12} /> Download Signed PDF
                                    </button>
                                </div>
                            </div>

                            <div className="relative flex gap-4">
                                <div className="absolute -left-[14px] w-8 h-8 rounded-full bg-[#0066FF] flex items-center justify-center border-4 border-[#0D1928] z-10">
                                    <Eye size={14} className="text-white" />
                                </div>
                                <div>
                                    <h4 className="font-bold text-white text-sm">Offer Viewed</h4>
                                    <p className="text-[11px] text-[#445566]">14 Mar 2025, 06:20 PM</p>
                                    <p className="text-xs text-[#8899AA] mt-1">Candidate opened the secure link generated via DocuSign.</p>
                                </div>
                            </div>

                            <div className="relative flex gap-4">
                                <div className="absolute -left-[14px] w-8 h-8 rounded-full bg-[#1A2A3A] flex items-center justify-center border-4 border-[#0D1928] z-10">
                                    <Send size={12} className="text-[#8899AA]" />
                                </div>
                                <div>
                                    <h4 className="font-bold text-[#8899AA] text-sm">Offer Sent</h4>
                                    <p className="text-[11px] text-[#445566]">14 Mar 2025, 04:00 PM</p>
                                    <p className="text-xs text-[#445566] mt-1">Offer generated by Priya Nair and emailed.</p>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div className="bg-[#0D1928] border border-[#1A2A3A] rounded-2xl p-6">
                        <h3 className="font-semibold text-sm mb-4">Background Verification (BGV) Status</h3>
                        {/* Empty state before triggering */}
                        <div className="flex items-center justify-between p-4 border border-dashed border-[#2A3A4A] rounded-xl bg-[#0A1420]">
                            <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-full bg-[#1A2A3A] flex items-center justify-center text-[#8899AA]">
                                    <Clock size={16} />
                                </div>
                                <div>
                                    <p className="font-medium text-white text-sm">Not Initiated</p>
                                    <p className="text-xs text-[#445566]">BGV link has not been sent yet</p>
                                </div>
                            </div>
                            <button className="h-9 px-4 bg-[#1A2A3A] text-white text-xs font-bold rounded-xl hover:bg-[#2A3A4A] transition-colors">Initiate BGV</button>
                        </div>
                    </div>
                </div>

                {/* Offer Summary Card */}
                <div className="space-y-6">
                    <div className="bg-[#0D1928] border border-[#1A2A3A] rounded-2xl p-6">
                        <h3 className="font-semibold text-sm mb-4">Final Offer Details</h3>

                        <div className="space-y-4">
                            <div className="flex items-start gap-3">
                                <div className="w-8 h-8 bg-[#1A2A3A] rounded-lg flex items-center justify-center shrink-0">
                                    <Briefcase size={14} className="text-[#8899AA]" />
                                </div>
                                <div>
                                    <p className="text-xs text-[#8899AA] mb-0.5">Role</p>
                                    <p className="text-sm font-semibold text-white">Senior Frontend Engineer</p>
                                </div>
                            </div>
                            <div className="flex items-start gap-3">
                                <div className="w-8 h-8 bg-[#1A2A3A] rounded-lg flex items-center justify-center shrink-0">
                                    <span className="text-[#8899AA] font-bold text-xs">₹</span>
                                </div>
                                <div>
                                    <p className="text-xs text-[#8899AA] mb-0.5">Total CTC</p>
                                    <p className="text-sm font-bold text-[#00E5A0]">₹32,00,000</p>
                                </div>
                            </div>
                            <div className="flex items-start gap-3">
                                <div className="w-8 h-8 bg-[#1A2A3A] rounded-lg flex items-center justify-center shrink-0">
                                    <Calendar size={14} className="text-[#8899AA]" />
                                </div>
                                <div>
                                    <p className="text-xs text-[#8899AA] mb-0.5">Joining Date</p>
                                    <p className="text-sm font-semibold text-white">15 April 2025</p>
                                </div>
                            </div>
                        </div>

                        <div className="mt-6 pt-6 border-t border-[#1A2A3A]">
                            <button className="w-full h-10 border border-[#2A3A4A] text-[#8899AA] hover:text-white rounded-xl text-sm font-medium transition-colors flex items-center justify-center gap-2">
                                <FileText size={14} /> View Original Document
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}

// Temporary shim for Calendar icon used above
function Calendar(props: any) {
    return <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect width="18" height="18" x="3" y="4" rx="2" ry="2" /><line x1="16" x2="16" y1="2" y2="6" /><line x1="8" x2="8" y1="2" y2="6" /><line x1="3" x2="21" y1="10" y2="10" /></svg>;
}
